network/urls.py
from django.urls import path

from . import views

app_name = 'network'

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("posts", views.allPosts, name="allPosts"),
    path("profile/<str:profile>", views.profile, name="profile"),
    path("following/<str:user>", views.following, name="following"),
    
    
    
    #API Routes
    path('post', views.post, name="post"),
    path('authenticated_user/', views.getAuthenticatedUser, name='authenticated_user'),
    path('add_follower/', views.addFollower, name='add_follower'),
    path('remove_follower/', views.removeFollower, name='remove_follower'),
    path('get_followers/', views.getFollowers, name='get_followers'),
    path('get_following/', views.getFollowing, name='get_following'),
    path('get_post', views.getPost, name='get_post'),
    path('save_edited_post', views.saveEditedPost, name='save_edited_post'),
    path('like', views.liked, name='like'),
    path('unlike', views.unlike, name='unlike'),
    
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser, models.Model):
    nickname = models.CharField(max_length=50, blank=True, null=True)
    followers = models.ManyToManyField('self', symmetrical=False, blank=True, related_name='following_users')
    following = models.ManyToManyField('self', symmetrical=False, blank=True, related_name='followers_users')
    liked_posts = models.ManyToManyField('Post', related_name='liking_users')
    
    def __str__(self):
        follower_names = [follower.username for follower in self.followers.all()]
        following_names = [following.username for following in self.following.all()]
        liked_posts_str = [str(post) for post in self.liked_posts.all()]

        liked_posts_str = ', '.join(liked_posts_str)
        
        return f"{self.username}  Liked Posts: {liked_posts_str}"
        # return f"{self.nickname} | Followers: {', '.join(follower_names)} | Following: {', '.join(following_names)}"
    

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    newPost = models.CharField(max_length=512)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.id} {self.newPost} {self.timestamp}"

network/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.core.paginator import Paginator

from .models import *


def index(request):
    posts = Post.objects.all().order_by('-timestamp')
    
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    return render(request, "network/index.html", {
        "posts": page_obj,
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        nickname = request.POST["nickname"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.nickname = nickname
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")

def allPosts(request):
    posts = Post.objects.all().order_by('-timestamp')
    
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    return render(request, "network/posts.html", {
        "posts": page_obj,
    })
    
def following(request, user):
    
    user = User.objects.get(username=user)
    following = user.following.all()
    # print(following)
    
    following_posts = []
    
    for post in following:
        following_post = post.posts.all()
        following_posts.extend(following_post)
        
    paginator = Paginator(following_posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
        
    
    return render(request, 'network/following.html', {
        "posts":  page_obj
    })
    
def profile(request, profile):
    # print(request.user)
    user_profile = User.objects.filter(username=profile).first()
    userPost = Post.objects.filter(user=user_profile).order_by('-timestamp')
    followers = user_profile.followers.all()
    following = user_profile.following.all()
    
    
    # print(len(following))
    
    return render(request, "network/profile.html", {
       "user_profile": user_profile,
       "userPost": userPost,
       "len_followers": len(followers),
       "len_following": len(following)
    })
 
@csrf_exempt    
def addFollower(request):
   if request.method == "POST":
       
       try:
            follower_data = json.loads(request.body)
            userPost = User.objects.get(username=follower_data['userPost'])
            
            user = request.user
            userDB = User.objects.get(username=user.username)
            if user not in userPost.followers.all() and user != userPost:
                userPost.followers.add(user)
                userDB.following.add(userPost)
                followers = userPost.followers.all()
                response = {'followers': len(followers)}
                return JsonResponse(response)
            # for f in userPost.followers.all():
            #     print(f.username)
                # print(userPost.followers.all())
            return JsonResponse({"message": "Follower recibida exitosamente"})
       except:
        return JsonResponse({"message": "Follower no recibida"})

@csrf_exempt 
def removeFollower(request):
    if request.method == 'POST':
        try:
            follower_data = json.loads(request.body)
            userPost = User.objects.get(username=follower_data['userPost'])
            
            user = request.user
            userDB = User.objects.get(username=user.username)
            if user in userPost.followers.all() and user != userPost:
                userPost.followers.remove(user)
                userDB.following.remove(userPost)
                followers = userPost.followers.all()
                response = {'followers': len(followers)}
                return JsonResponse(response)
            # for f in userPost.followers.all():
            #     print(f.username)
                print(userPost.followers.all())
                return JsonResponse({"message": "Follower removed succesfully"})
            else:
                return JsonResponse({"message": "User is not a follower"})
        
        except:
            return JsonResponse({"message": "Follower no recibida"})
        
    

@csrf_exempt
def getAuthenticatedUser(request):
    if request.method == "GET":
        authenticated_user = {
            "id": request.user.id,
            "username": request.user.username,
            "email": request.user.email,
            "nickname": request.user.nickname,
        }
        
        return JsonResponse(authenticated_user)
    else:
        return JsonResponse({"error": "GET request required."}, status=400)

@csrf_exempt
def post(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            user = request.user
            comment = data.get('post')
            if comment:
                posting = Post(user=user, newPost=comment)
                posting.save()    
                print(posting)
                return JsonResponse({"post": {
                    "id": posting.id,
                    "user": posting.user.username,
                    "nickname": posting.user.nickname,
                    "timestamp": posting.timestamp 
                    }
                })
                # return JsonResponse({"message": "Publication received successfully"})
            else:
                return JsonResponse({"error": "Comment not provided."}, status=400)
        except json.JSONDecodeError:
            return JsonResponse({"error": "Invalid JSON format."}, status=400)
    else:
        return JsonResponse({"error": "A POST request is required."}, status=400)

@csrf_exempt
def getFollowers(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            # print(data)
            userPost = User.objects.get(username=data['userPost'])
            followers = userPost.followers.all()
            print(len(followers))
            response = {'followers': [{'username': follower.username, 'nickname': follower.nickname} for follower in followers]}
            return JsonResponse(response)
        except:
            return JsonResponse({"error": "Invalid JSON format."}, status=400)
    else:
        return JsonResponse({"error": "A POST request is required."}, status=400)
    
    
@csrf_exempt
def getFollowing(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            # print(data)
            userPost = User.objects.get(username=data['userPost'])
            following = userPost.following.all()
            response = {'following': [{'username': follow.username, 'nickname': follow.nickname} for follow in following]}
            return JsonResponse(response)
        except:
            return JsonResponse({"error": "Invalid JSON format."}, status=400)
    else:
        return JsonResponse({"error": "A POST request is required."}, status=400)
   
   
@csrf_exempt    
def getPost(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            
            post = Post.objects.get(id = data)
            response = {"post": post.newPost}
            
            return JsonResponse(response)
            # return JsonResponse({"message": "Follower removed succesfully"})
        except:
            return JsonResponse({"error": "Invalid JSON format."}, status=400)
    else:
        return JsonResponse({"error": "A POST request is required."}, status=400)
    

@csrf_exempt      
def saveEditedPost(request):
    if request.method == "POST":
        
        try:
            data = json.loads(request.body)
            post_user = Post.objects.get(id=data['id'])
            user= request.user
            # print(post_user.user)
            
            if(user == post_user.user):
                post_user.newPost = data['newPost']
                post_user.save()
            return JsonResponse({"message": "Post saved succesfully"})
            
        except:
            return JsonResponse({"error": "Invalid JSON format."}, status=400)
        
    else:
        return JsonResponse({"error": "A POST request is required."}, status=400)
        
        

@csrf_exempt 
def liked(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)

network/templates/network/following.html
{% extends "network/layout.html" %} {% load static %} {% block body %}
<div class="container-md">
  <div class="row no-gutters">
    {% for post in posts %}
    <div class="col-12 post-wrapper my-4">
        <div class="d-flex justify-content-between">
          <div>
            <a
              href="{% url 'network:profile' post.user.username  %}"
              class="mr-2 font-weight-bold profile-link"
              >{{ post.user.nickname }}</a
            >
            <span class="username-text">@{{ post.user.username }}</span>
          </div>
          <span class="date-info">{{ post.timestamp}}</span>
        </div>
        <p class="mt-3">{{ post.newPost }}</p>
        <i class="fa-solid fa-heart like-heart mr-3"></i>
        <i class="fa-regular fa-heart like-heart mr-3"></i>
        <i class="fa-solid fa-comment mr-3"></i>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-center pb-5">
      <div class="pagination my-5 justify-content-center">
        <span class="step-links">
          <div class="d-flex">
            {% if posts.has_previous %}
            <a class="btn-pagination p-2 rounded" href="?page=1"
              >&laquo; first</a
            >
            <a
              class="btn-pagination p-2 rounded"
              href="?page={{ posts.previous_page_number }}"
              >previous</a
            >
            {% endif %} {% if posts.has_next %}
            <a
              class="btn-pagination p-2 rounded"
              href="?page={{ posts.next_page_number }}"
              >next</a
            >
            <a
              class="btn-pagination p-2 rounded"
              href="?page={{ posts.paginator.num_pages }}"
              >last &raquo;</a
            >
            {% endif %}
          </div>
          <span class="current mt-2 d-block">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
          </span>
        </span>
      </div>
    </div>
  </div>
</div>






{% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %} {% load static %} {% block body %}

<div class="container-md">
  <div class="row">
    <div class="col-12">
      <div class="mb-3">
        <form action="{% url 'network:post' %}" method="post">
          {% csrf_token %}
          <textarea
            class="form-control text-white"
            id="mainPost"
            rows="3"
            placeholder="What are you thinking? &#129300;"
          ></textarea>
          <button
            type="button"
            class="btn d-block ml-auto mt-4"
            id="postBtn"
            data-url="{% url 'network:post' %}"
          >
            Post
          </button>
        </form>
      </div>
    </div>
  </div>

  <div id="currentPosted"></div>

  <div class="row no-gutters" id="postRow">
    {% for post in posts %}
    <div class="col-12 post-wrapper my-4">
      <div class="d-flex justify-content-between">
        <div>
          <a
            href="{% url 'network:profile' post.user.username  %}"
            class="mr-2 font-weight-bold profile-link"
            >{{ post.user.nickname }}</a
          >
          <span class="username-text">@{{ post.user.username }}</span>
        </div>
        <span class="date-info">{{ post.timestamp}}</span>
      </div>
      <p class="mt-3" id="edit_{{post.id}}">{{ post.newPost }}</p>
      <div id="editContent{{post.id}}" class="d-none mt-2">
        <div class="d-flex justify-content-end">
          <i
            class="fa-solid fa-circle-xmark mb-2 pointer closeEdit"
            data-post="{{post.id}}"
          ></i>
        </div>
        <textarea
          class="form-control edit-post-textarea"
          id="textArea{{post.id}}"
          rows="3"
        ></textarea>

        <button
          type="button"
          class="btn d-block ml-auto mt-4 editPostBtn"
          data-post="{{post.id}}"
        >
          save
        </button>
      </div>
      <p>{{user }}</p>

      <i
        class="fa-solid fa-heart like-heart mr-1 addedLike pointer removeLike {% if user in post.liking_users.all %} d-inline-block {% else %} d-none {% endif %}"
        id="removeLike-{{post.id}}"
        data-user="{{user.username}}"
        data-post="{{post.id}}"
      ></i>
      {% if user.is_authenticated %}
      <i
        class="fa-regular fa-heart like-heart mr-1 pointer addLike {% if user not in post.liking_users.all %} d-inline-block {% else %} d-none {% endif %}"
        id="addLike-{{post.id}}"
        data-user="{{user.username}}"
        data-post="{{post.id}}"
      ></i>

      {% else %}
      <i class="fa-regular fa-heart like-heart mr-1"></i>

      {% endif %}

      <span class="mr-3" id="nPost-{{post.id}}"
        >{{ post.liking_users.count }}</span
      >
      <i
        class="fa-regular fa-pen-to-square pointer editPost"
        data-post="{{post.id}}"
      ></i>
    </div>
    {% endfor %}
  </div>
  <div class="row">
    <div class="col-12 text-center pb-5">
      <div class="pagination my-5 justify-content-center">
        <span class="step-links">
          <div class="d-flex">
            {% if posts.has_previous %}
            <a class="btn-pagination p-2 rounded" href="?page=1"
              >&laquo; first</a
            >
            <a
              class="btn-pagination p-2 rounded"
              href="?page={{ posts.previous_page_number }}"
              >previous</a
            >
            {% endif %} {% if posts.has_next %}
            <a
              class="btn-pagination p-2 rounded"
              href="?page={{ posts.next_page_number }}"
              >next</a
            >
            <a
              class="btn-pagination p-2 rounded"
              href="?page={{ posts.paginator.num_pages }}"
              >last &raquo;</a
            >
            {% endif %}
          </div>
          <span class="current mt-2 d-block">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
          </span>
        </span>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'network/network.js' %}"></script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Social Network{% endblock %}</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'network/n-logo.jpg' %}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <meta charset="UTF-8" />
    <link href="{% static 'network/styles.css' %}" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
      integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>
  <body>
    <div class="main-wrapper">
      <nav class="network-nav nav-md text-center">
        <a class="brand" href="{% url 'network:index' %}">Network</a>

        <div>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link"
                href="{% url 'network:profile' user.username %}"
                ><strong>{{ user.username }}</strong></a
              >
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'network:allPosts' %}"
                >All Posts</a
              >
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link"
                href="{% url 'network:following' user.username %}"
                >Following</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'network:register' %}"
                >Register</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      <div class="body">{% block body %} {% endblock %}</div>
    </div>
  </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %} {% block body %}

<h2>Login</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'network:login' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <input
      autofocus
      class="form-control"
      type="text"
      name="username"
      placeholder="Username"
    />
  </div>
  <div class="form-group">
    <input
      class="form-control"
      type="password"
      name="password"
      placeholder="Password"
    />
  </div>
  <input class="btn btn-primary" type="submit" value="Login" />
</form>

Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/posts.html
{% extends "network/layout.html" %} {% block body %}
<div class="container-md">
  <div class="row no-gutters" id="postRow">
    {% for post in posts %}
    <div class="col-12 post-wrapper my-4">
      <div class="d-flex justify-content-between">
        <div>
          <a
            href="{% url 'network:profile' post.user.username  %}"
            class="mr-2 font-weight-bold profile-link"
            >{{ post.user.nickname }}</a
          >
          <span class="username-text">@{{ post.user.username }}</span>
        </div>
        <span class="date-info">{{ post.timestamp}}</span>
      </div>
      <p class="mt-3">{{ post.newPost }}</p>
      <i class="fa-solid fa-heart like-heart mr-3"></i>
      <i class="fa-regular fa-heart like-heart mr-3"></i>
      <i class="fa-solid fa-comment mr-3"></i>
    </div>
    {% endfor %}
  </div>
</div>
<div class="row">
  <div class="col-12 text-center pb-5">
    <div class="pagination my-5 justify-content-center">
      <span class="step-links">
        <div class="d-flex">
          {% if posts.has_previous %}
          <a class="btn-pagination p-2 rounded" href="?page=1">&laquo; first</a>
          <a
            class="btn-pagination p-2 rounded"
            href="?page={{ posts.previous_page_number }}"
            >previous</a
          >
          {% endif %} {% if posts.has_next %}
          <a
            class="btn-pagination p-2 rounded"
            href="?page={{ posts.next_page_number }}"
            >next</a
          >
          <a
            class="btn-pagination p-2 rounded"
            href="?page={{ posts.paginator.num_pages }}"
            >last &raquo;</a
          >
          {% endif %}
        </div>
        <span class="current mt-2 d-block">
          Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>
      </span>
    </div>
  </div>
</div>
{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %} {% load static %} {% block body %}

<div class="d-flex justify-content-between pb-5">
  <div>
    <h1 class="profile-username">{{ user_profile.username }}</h1>
    <h4 class="profile-nickname">@{{ user_profile.nickname }}</h4>
    <p class="mb-0 social-length" id="followerLength">
      {{ len_followers }} Followers
    </p>
    <p class="mb-0 social-length" id="fetchFollowerLength"></p>
    <p class="mb-0 social-length" id="followingLength">
      {{ len_following }} Following
    </p>
    <p class="mb-0 social-length" id="fetchFollowingLength"></p>
  </div>
  {% if user.is_authenticated and user != user_profile %}
  <button
    class="btn profile-btn {% if user not in user_profile.followers.all %} d-block {% else %} d-none {% endif %}"
    id="addFollower"
    data-user="{{ user_profile.username }}"
  >
    Follow
  </button>

  <button
    class="btn profile-btn {% if user in user_profile.followers.all %} d-block {% else %} d-none {% endif %}"
    id="removeFollower"
    data-user="{{ user_profile.username }}"
  >
    Unfollow
  </button>
  {% endif %}
</div>

<ul class="nav nav-tabs mt-5 d-flex justify-content-center">
  <li class="nav-item mx-3">
    <a class="nav-link active" href="#" id="posts">Posts</a>
  </li>
  <li class="nav-item mx-3">
    <a
      class="nav-link"
      href="#"
      data-user="{{ user_profile.username }}"
      id="followers"
      >Followers</a
    >
  </li>
  <li class="nav-item mx-3">
    <a
      class="nav-link"
      href="#"
      data-user="{{ user_profile.username }}"
      id="following"
      >Following</a
    >
  </li>
</ul>

<div id="postRow" class="d-block">
  <div class="row no-gutters">
    {% for post in userPost %}
    <div class="col-12 post-wrapper mb-4 mt-5">
      <div class="d-flex justify-content-between">
        <div>
          <a
            href="{% url 'network:profile' post.user.username  %}"
            class="mr-2 font-weight-bold profile-link"
            >{{ post.user.nickname }}</a
          >
          <span class="username-text">@{{ post.user.username }}</span>
        </div>
        <span class="date-info">{{ post.timestamp}}</span>
      </div>
      <p class="mt-3">{{ post.newPost }}</p>
      <i class="fa-solid fa-heart like-heart mr-3"></i>
      <i class="fa-regular fa-heart like-heart mr-3"></i>
      <i class="fa-solid fa-comment mr-3"></i>
    </div>
    {% endfor %}
    <script src="{% static 'network/profile.js' %}"></script>
  </div>
</div>

<div class="d-none" id="followersWarpper">
  <div class="text-center mt-4">
    <div
      class="spinner-border text-primary d-none"
      role="status"
      id="followersSpinner"
    >
      <span class="sr-only">Loading...</span>
    </div>
  </div>
  <div id="followersInnerWarpper"></div>
</div>

<div class="d-none" id="followingWarpper">
  <div class="text-center mt-4">
    <div
      class="spinner-border text-primary d-none"
      role="status"
      id="followingSpinner"
    >
      <span class="sr-only">Loading...</span>
    </div>
  </div>
  <div id="followingInnerWarpper"></div>
</div>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %} {% block body %}

<h2>Register</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'network:register' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <input
      class="form-control"
      autofocus
      type="text"
      name="username"
      placeholder="Username"
    />
  </div>
  <div class="form-group">
    <input
      class="form-control"
      autofocus
      type="text"
      name="nickname"
      placeholder="Nickname"
    />
  </div>
  <div class="form-group">
    <input
      class="form-control"
      type="email"
      name="email"
      placeholder="Email Address"
    />
  </div>
  <div class="form-group">
    <input
      class="form-control"
      type="password"
      name="password"
      placeholder="Password"
    />
  </div>
  <div class="form-group">
    <input
      class="form-control"
      type="password"
      name="confirmation"
      placeholder="Confirm Password"
    />
  </div>
  <input class="btn btn-primary" type="submit" value="Register" />
</form>

Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}